In [1]:
import numpy as np
import pandas as pd
import statistics as stats
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
M1= np.random.randint(1, 50, size=(3, 3))
M1

array([[28, 13, 45],
       [13,  5, 33],
       [10,  2,  5]])

In [3]:
M1+50

array([[78, 63, 95],
       [63, 55, 83],
       [60, 52, 55]])

In [4]:
M1-20

array([[  8,  -7,  25],
       [ -7, -15,  13],
       [-10, -18, -15]])

In [5]:
M1*3

array([[ 84,  39, 135],
       [ 39,  15,  99],
       [ 30,   6,  15]])

In [6]:
M1/4

array([[ 7.  ,  3.25, 11.25],
       [ 3.25,  1.25,  8.25],
       [ 2.5 ,  0.5 ,  1.25]])

In [7]:
N1 = np.random.randint(1, 50, size=(3, 3))
N2 = np.random.randint(1, 50, size=(3, 3))
print("first Matrix is : ", N1, "\nSecond Matrix is : ", N2)

first Matrix is :  [[29 21  5]
 [ 6 38 40]
 [29  7  3]] 
Second Matrix is :  [[47 30 46]
 [38  2 25]
 [ 4 34 14]]


In [8]:
N1+N2

array([[76, 51, 51],
       [44, 40, 65],
       [33, 41, 17]])

In [9]:
N1-N2

array([[-18,  -9, -41],
       [-32,  36,  15],
       [ 25, -27, -11]])

In [10]:
N1*N2

array([[1363,  630,  230],
       [ 228,   76, 1000],
       [ 116,  238,   42]])

In [11]:
N1/N2

array([[ 0.61702128,  0.7       ,  0.10869565],
       [ 0.15789474, 19.        ,  1.6       ],
       [ 7.25      ,  0.20588235,  0.21428571]])