In [1]:
import numpy as np

In [2]:
np.arange(0,24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [4]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
arr3d.ndim

3

In [5]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
arr2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2.shape

(3, 3)

In [8]:
arr2.size

9

In [9]:
arr2.ndim

2

In [10]:
arr2.dtype

dtype('int64')

In [11]:
array2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]] ,dtype=float)

In [12]:
array2.dtype

dtype('float64')

In [13]:
farr = np.array([3,6,2,5])

In [14]:
farr.shape

(4,)

In [15]:
farr[1]=40
farr

array([ 3, 40,  2,  5])

In [16]:
np.arange(1,11)  # kind of (for loop with range)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,10,4)  # start end num : (from 1 - 10 distributes equely) num times = 4 times

array([ 1.,  4.,  7., 10.])

In [18]:
emp = np.empty(6)  
emp

array([2.41907520e-312, 1.06099790e-312, 2.33419537e-312, 2.22809558e-312,
       2.67020950e-306, 2.08388517e-134])

In [19]:
np.ones((6,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.full((5,2), 3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [22]:
np.array([3,5,7,2])

array([3, 5, 7, 2])

In [23]:
sanu = np.zeros((5,3))
sanu

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
sanu.ndim

2

In [25]:
a = np.zeros((2, 5, 3, 4))
a.ndim

4

In [26]:
np.random.rand(7)

array([0.16287696, 0.49580745, 0.20290694, 0.44218501, 0.51200452,
       0.54875967, 0.28140135])

In [27]:
j = np.arange(10)
j[9]

np.int64(9)

In [28]:
a = np.diag([1,2,3])
print(a)
print(f"Index of a 2x2 is : {a[2, 2]}")

[[1 0 0]
 [0 2 0]
 [0 0 3]]
Index of a 2x2 is : 3


In [29]:
a[2, 1] = 6   #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 6, 3]])

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a[1:8:2]  #start=1, end=8, step=2 

array([1, 3, 5, 7])

In [32]:
#combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [33]:
b = np.arange(5)
a[5:] = b[::-1] #assigning into a the reverse value of b 
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and Views
A slicing operation created a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

<b>When modigying the view, the original array is modified as well:<b>

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = a[::2]  #storing indexes of 'a' along with there idx val in 'b'
b

array([0, 2, 4, 6, 8])

In [36]:
np.shares_memory(a,b) #as there indexes are same and stored 'a' val into 'b' , there memory location are same, output=True

True

In [37]:
b[0] = 10
print(b)
print(a)  #eventhough we modified 'b', it updated 'a' because both shares same memory

#the chanages in 'b' will be reflect in 'a' also because 'b' stores the values of 'a', which makes memory location same for both : a & b

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [38]:
a = np.arange(10)

#force a copy
c = a[::2].copy()  #here we are just forcefuly copying the value of 'a' into 'c'
c

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,c)  #output:false, because we just copied the val, so that is why there memory location are not same

False

In [40]:
c[0] = 10  #assigning new val
a  #assigning val in 'c' will not reflect in 'a' because there memory location are not same

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy Indexing
Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates couples not views.

<b>Using Boolean Mask<b>

In [41]:
a = np.random.randint(0, 20, 15)
a

array([13,  9, 14, 10,  9, 13, 16, 12, 16, 13,  8, 16, 11,  9,  8],
      dtype=int32)

In [42]:
mask = (a % 2 == 0)

In [43]:
#extracting mask variable operation
extract_from_a = a[mask]
extract_from_a

array([14, 10, 16, 12, 16,  8, 16,  8], dtype=int32)

<b> Indexing with a mask can be very useful to assign a new value to a sub-array: <b>

In [44]:
a[mask] = -1  #assigning 'mask' value with -1
a

array([13,  9, -1, -1,  9, 13, -1, -1, -1, 13, -1, -1, 11,  9, -1],
      dtype=int32)

<b>Indexing with an array of integers<b>

In [45]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [47]:
# New values can be assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Practice Questions (Easy)

In [48]:
# Create a 1D NumPy array of numbers from 0 to 9.
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# Create a 3×3 NumPy array filled with all True values (Boolean type).
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
# Create a 2D NumPy array with shape (3, 3) containing random integers from 1 to 10 (inclusive).
np.random.randint(1, 11, size=(3, 3))

array([[4, 6, 1],
       [7, 2, 8],
       [3, 2, 7]], dtype=int32)

In [51]:
# Create a 1D NumPy array with 10 values evenly spaced between 0 and 1, inclusive.
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [52]:
# Create a 3×3 identity matrix using NumPy.
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# Given a NumPy array a = np.array([1, 2, 3, 4, 5]), how would you get a new array with the elements reversed?
a = np.arange(1,6)
a[::-1]

array([5, 4, 3, 2, 1])

In [54]:
# How would you reshape a 1D array of 9 elements into a 3×3 2D array using NumPy?
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
# How can you extract all even numbers from the NumPy array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])?

#Using Boolean Indexing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = (a % 2 == 0)
print(a[b])

[2 4 6 8]


In [56]:
# How can you extract all even numbers from the NumPy array a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])?

#Using Boolean Indexing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
approach = a[a % 2 == 0]
print(approach)

[2 4 6 8]


In [57]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# ChatGPT Basic Practice Questions

In [58]:
# Q: Create a 1D NumPy array of integers from 0 to 9 and print only the even numbers.
d = np.arange(9)
print(d[d % 2 == 0])

[0 2 4 6 8]


In [59]:
# Q: Create a 1D NumPy array of integers from 10 to 20 (inclusive) and print only the numbers that are divisible by 3.
d = np.arange(10, 21)
print(d[d % 3 == 0])

[12 15 18]


In [60]:
# Q: Create a 1D NumPy array of 5 random integers between 1 and 100 (inclusive), and print the maximum and minimum values from the array.
d = np.random.randint(1, 101, 5)
print(d)

[77  4 72 67  3]


In [61]:
# Q: Create a 1D NumPy array of 10 numbers linearly spaced between 0 and 1 (inclusive), and print the array.
d = np.linspace(0, 2, 10)
print(d)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [62]:
# Q: Create a 3x3 NumPy array with values from 1 to 9, and print the sum of each row.
d = np.arange(1, 10)       
d = d.reshape(3, 3)          
print("Array:\n", d)
print("Row-wise sum:", d.sum(axis=1))

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row-wise sum: [ 6 15 24]


In [63]:
# Q: Create a 4x4 NumPy array with values from 1 to 16, and print the elements on its main diagonal.
d = np.arange(1, 17)
d = d.reshape(4, 4)
print("Array:\n", d)
print("Main diagonal:", np.diag(d))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Main diagonal: [ 1  6 11 16]


In [64]:
# Q: Create a 1D NumPy array with values [3, 7, 1, 9, 2], and sort the array in ascending order.
a = np.array([3, 7, 1, 9, 2])
sorted_a = np.sort(a)
print("Original array:", a)
print("Sorted array:  ", sorted_a)

Original array: [3 7 1 9 2]
Sorted array:   [1 2 3 7 9]


In [65]:
# Q1: Create a 1D NumPy array with values from 0 to 20 (inclusive), and print only the values that are divisible by 4.
arr1 = np.arange(0, 21)
print("Numbers divisible by 4:", arr1[arr1 % 4 == 0])

Numbers divisible by 4: [ 0  4  8 12 16 20]


In [66]:
# Q2: Create a 3x3 NumPy array with values from 1 to 9, and print the sum of all elements.
arr2 = np.arange(1, 10).reshape(3, 3)
print("3x3 Array:\n", arr2)
print("Sum of all elements:", arr2.sum())

3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
