In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Valid Sudoku

In [22]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [23]:
b = np.sum(s, axis = 1)  # axis = 1 is for rows
for i in b:
    if i != 45:
        print("Sudoku is not valid!")
    else:
        print("For rows it is valid.")
        break

For rows it is valid.


In [24]:
s[0:3, 0:3]  # for index slicing, first slicing for rows and second for columns

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [25]:
s[0:3, 3:6]  # index slicing, first slicing for rows and second for columns

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [26]:
s[0:3, 6:9]  # index slicing, first slicing for rows and second for columns

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [27]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [28]:
# making 3X3 array of s using loop wise slicing
for i in range(0, 9, 3):  # for rows
    for j in range(0, 9, 3):  # for columns
        print(s[i:i+3,j:j+3])  # s[start_row : end_row, start_column : end_column]

# in official Numpy slicing of array format are mention below 
# s[rows, columns] 

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


### General Questions

In [29]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
]) 

In [30]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [31]:
# Find the average age of students.
np.mean(data[:, 0])

18.4

In [32]:
# Extract Math marks of all students.
data[:, 1]

array([85, 92, 76, 65, 90])

In [33]:
# Find the highest Science mark.
np.max(data[:, 2])

95

In [34]:
# Get details of the student who scored more than 90 in Math.
data[data[:, 1] > 90]

# output will be the full data of student who scored > 90 in maths

array([[19, 92, 88]])

In [35]:
# Increase Math marks of all students by 5.
print(data[:, 1] + 5)  # for temp change which will not reflect in original 'data' variable

[90 97 81 70 95]


In [36]:
data[:, 1] += 5  # for permanent change which will make changes in 'data' variable column 1 = Maths column
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [37]:
# Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [38]:
# Calculate the average marks in each subject (column-wise mean).
np.mean(data[:, 1:], axis = 0)  # axis=0 for col wise

array([86.6, 83.2])

In [39]:
# Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]   # condition for both columns maths and science

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [40]:
# Replace all Science marks < 75 with 0.
data[:, 2][data[:, 2] < 75] = 0  # We select the col first, give the condition, if found then those particular val converted into 0
data   # student who score < 75 in science, we converted those science score with 0

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])